kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: deploy-and-test
spec:
  description: |
    An integration test which provisions an ephemeral namespace and deploys a container from a Konflux snapshot.
  params:
    - description: Snapshot of an application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: Namespace where the container will be deployed.
      name: NAMESPACE
      default: default
      type: string
    - description: Name of the pod and service to be tested (oc expose gives the service the same name as the pod)
      name: pod-and-svc-name
      default: trex
      type: string
  tasks:
    - name: provision-namespace
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/provision-env-with-ephemeral-namespace/0.1/provision-env-with-ephemeral-namespace.yaml
      params:
        - name: KONFLUXNAMESPACE
          value: $(context.pipelineRun.namespace)
        - name: PIPELINERUN_NAME
          value: $(context.pipelineRun.name)
        - name: PIPELINERUN_UID
          value: $(context.pipelineRun.uid)
    - name: deploy-container
      runAfter:
        - provision-namespace
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/jencull/rh-trex.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/tasks/deploy.yaml
      params:
        - name: serviceaccount-secret
          value: $(tasks.provision-namespace.results.secretRef)
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: pod-name
          value: $(params.pod-and-svc-name)
    - name: hello-world
      runAfter: 
        - deploy-container
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/jencull/rh-trex.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/tasks/sample-task.yaml
    - name: port-forward
      runAfter:
        - hello-world
      taskSpec:
        steps:
          - name: port-forward
            image: registry.redhat.io/openshift4/ose-cli:latest
            script: |
              #!/usr/bin/env bash
              echo "${KUBECONFIG_VALUE}" > /tmp/kubeconfig
              export KUBECONFIG=/tmp/kubeconfig
              oc port-forward svc/$(params.pod-and-svc-name) 8080:8000 &
              # Wait briefly to ensure the port-forward is established
              sleep 10
        params:
          - name: KUBECONFIG_VALUE
            description: Kubeconfig file for accessing the cluster
            type: string
          - name: pod-and-svc-name
            description: Name of the pod and service
            default: trex
    - name: run-test
      runAfter:
        - port-forward
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/jencull/rh-trex.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/rapidast/rapidast-test.yaml
      params:
        - name: serviceaccount-secret
          value: $(tasks.provision-namespace.results.secretRef)
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: svc-name
          value: $(params.pod-and-svc-name)
        - name: endpoint
          value: http://127.0.0.1:8080
