apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-container
spec:
  params:
    - name: serviceaccount-secret
      description: "Secret to service account that can access the ephemeral namespace"
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
    - name: pod-name
      description: Name of the pod and service to be tested
  steps:
    - name: deploy-container
      image: registry.redhat.io/openshift4/ose-cli:latest
      imagePullPolicy: Always
      env:
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SECRETNAME
          value: $(params.serviceaccount-secret)
        - name: PODNAME
          value: $(params.pod-name)
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail

        echo "Using secretRef in deploy-container: $SECRETNAME"

        # Export the kubeconfig using the secret
        oc get secret $SECRETNAME --template '{{.data.kubeconfig}}' | base64 -d > /kubeconfig
        export KUBECONFIG=/kubeconfig

        # Install dependencies
        dnf install -y jq gettext --disableplugin=subscription-manager

        # Extract container image from snapshot
        export COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")

        # Fetch, resolve, and log the pod-and-svc.yaml content
        echo "Fetching and resolving pod-and-svc.yaml..."
        curl https://raw.githubusercontent.com/jencull/rh-trex/main/.tekton/integration/pod-and-svc.yaml | envsubst > resolved-pod-and-svc.yaml

        echo "Resolved pod-and-svc.yaml content:"
        cat resolved-pod-and-svc.yaml

        # Apply the pod and service YAML
        oc apply -f resolved-pod-and-svc.yaml


        # Wait for the pod to be ready using `oc wait`
        echo "Waiting for pod $PODNAME to be ready..."
        oc wait --for=condition=Ready pod/$PODNAME --timeout=240s

        # Port forward from local port 8000 to pod port 8080
        echo "Starting port forward..."
        oc port-forward --kubeconfig /kubeconfig pod/$PODNAME 8080:8000 &

        # Wait briefly to establish the port-forward
        sleep 20

        # Test the application using localhost:8080
        echo "Testing application at http://localhost:8000"
        curl -X GET -s http://localhost:8080 | jq
    